#!/bin/bash

cd /usr/share/python3
. venv/bin/activate

export FLASK_APP=wsgi.py

flask db init
flask db migrate
flask db upgrade

# 15 minutes timeout - for extra large models
TIMEOUT=900

gunicorn wsgi:app --bind 0.0.0.0:5000 --timeout $TIMEOUT
